name: black formatter
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Installing black and format code
        run: pip install git+https://github.com/psf/black
      - name: Format code
        run: python -m black .
    
      - name: push changes
        run: |
          git config --global user.name "Black formatter"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "Apply black formatted code"
          git push
